name: CI Todo
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      -
        name: Install dependency
        run: yarn install
      -
        name: Run the tests and generate coverage report
        run: CI=true yarn test
      - 
        name: build
        run: yarn build